name: Deploy to Firebase Hosting on PR
'on': pull_request

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build  # This already outputs to dist/
          # Verify the dist directory exists
          ls -la dist/
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LANDSPICE }}'
          channelId: 'pr-${{ github.event.pull_request.number }}'
          projectId: 'landspice-d9db5'  # Replace with your Firebase project ID
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

---
name: Deploy to Firebase Hosting on Push
'on':
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build  # This already outputs to dist/
          # Verify the dist directory exists
          ls -la dist/
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LANDSPICE }}'
          channelId: live
          projectId: 'landspice-d9db5'  # Replace with your Firebase project ID
          site: 'landspice'
